version : '3'
services:
  server:
    image: 154114/niyo
    ports:
      - "3000:3000"
    environment:
        DATABASE_URL: "postgresql://admin:admin@web_db:5432/niyo"
    depends_on: ['web_db'] 
    command: >
        sh -c "
        npx  prisma migrate deploy &&
        npx prisma generate &&
        npm start
        "
  
  web_db:
    image: postgres
    expose:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
       POSTGRES_USER: "admin"
       POSTGRES_PASSWORD: "admin"
       POSTGRES_DB: "niyo"

    restart: always

volumes:
 postgres: {}