version : '3'
services:
  server:
    image: 15/4114:niyo
    ports:
      - "3000:3000"
    environment:
        DATABASE_URL: "postgresql://guest:guest@web_db:5432/niyo"
    depends_on: ['web_db'] 
  
  web_db:
    image: postgres:13.5
    networks:
      - "postgres-db"
    expose:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
       POSTGRES_USER: "guest"
       POSTGRES_PASSWORD: "guest"
       POSTGRES_DB: "niyo"

    restart: always

volumes:
 postgres: {}