# This workflow is to test the niyo  service

name: Niyo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [16.x, 18.x]
    
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: admin
          POSTGRES_DB: niyo

        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
  
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

      env: 
        DATABASE_URL:  postgresql://admin:admin@postgres:5432/niyo
    - name: Install Packages
      run: |
         npm install

    - name: Prisma Migrate 
      run: |
         npx prisma generate

    - name: Build
      run: |
         npm run build
    
    - name : Test
      run: |
         npm run test
   